"""empty message

Revision ID: d3e002b6197a
Revises: 53997054a985
Create Date: 2026-05-23 02:49:04.215811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd3e002b6197a'
down_revision: Union[str, Sequence[str], None] = '53997054a985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expediente', schema=None) as batch_op:
        batch_op.alter_column('servicios_activos',
               nullable=False,
               existing_server_default=sa.text("''::text"))
        batch_op.alter_column('servicios_inactivos',
               nullable=False,
               existing_server_default=sa.text("''::text"))
        batch_op.alter_column('constancia_estudios',
               nullable=False,
               existing_server_default=sa.text("''::text"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expediente', schema=None) as batch_op:
        batch_op.alter_column('constancia_estudios',
               nullable=True,
               existing_server_default=sa.text("''::text"))
        batch_op.alter_column('servicios_inactivos',
               nullable=True,
               existing_server_default=sa.text("''::text"))
        batch_op.alter_column('servicios_activos',
               nullable=True,
               existing_server_default=sa.text("''::text"))

    # ### end Alembic commands ###
