"""empty message

Revision ID: f225eb19140e
Revises: 531acaeb38c6
Create Date: 2026-05-23 02:12:51.018532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f225eb19140e'
down_revision: Union[str, Sequence[str], None] = '531acaeb38c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expediente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('curp', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rfc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('sexo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('etapa', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dictamen', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('motivo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sello_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('finado', sa.Boolean(), nullable=False),
    sa.Column('score_biometrico', sa.Float(), nullable=False),
    sa.Column('programa_recomendado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('analisis_ia', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha_registro', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expediente')
    # ### end Alembic commands ###
